//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquileres_de_peliculas_HD.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquileres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alquileres()
        {
            this.Detalle = new HashSet<Detalle>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int id { get; set; }
        public int FK_id_usuario { get; set; }
        public int FK_id_cliente { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public bool Estado { get; set; }
        public int Total { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
