//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquileres_de_peliculas_HD.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int FK_id_alquileres { get; set; }
        public int FK_id_peliculas { get; set; }
        public int idDetalle { get; set; }
    
        public virtual Alquileres Alquileres { get; set; }
        public virtual Peliculas Peliculas { get; set; }
    }
}
