//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquileres_de_peliculas_HD.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public int monto { get; set; }
        public int FK_id_Alquiler { get; set; }
    
        public virtual Alquileres Alquileres { get; set; }
    }
}
